//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeFive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTransfer
    {
        public int TransferID { get; set; }
        public int TransferMemberID { get; set; }
        public bool TransferDone { get; set; }
        public string TransferPictures { get; set; }
        public int TransferPosition { get; set; }
        public bool TransferGender { get; set; }
        public string TransferName { get; set; }
        public int TransferSpecies { get; set; }
        public bool TransferNeuter { get; set; }
        public string TransferSituation { get; set; }
        public string TransferRequest { get; set; }
        public string TransferContactWay { get; set; }
        public string TransferContactPerson { get; set; }
        public System.DateTime Created_At { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tPosition tPosition { get; set; }
        public virtual tSpecies tSpecies { get; set; }
    }
}
